global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'infra-terrarium'
    environment: 'dev'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alloy-node-exporter'
    file_sd_configs:
      - files:
          - '/opt/observability/prometheus-targets.json'
        refresh_interval: 30s
    scrape_interval: 15s
    metrics_path: '/metrics'
